-- Agent-level social/platform connections (e.g. a Facebook Page + Graph API
-- token) and per-listing syndication tracking, so a listing created in
-- list-property.html can be auto-posted to a connected platform and we know
-- what happened when it was.
--
-- Tokens are sensitive: the base table has RLS enabled with NO policies for
-- anon/authenticated, so only the service_role key (used from a Netlify
-- function, never the browser) can read or write it. A separate status view
-- exposes only the non-secret columns so the UI can show a "Connected" badge
-- without ever handling the token. This mirrors the courtesy_line /
-- public_listings pattern already used in the Abrevo project.

create table if not exists agent_integrations (
  id uuid primary key default gen_random_uuid(),
  agent_id uuid references profiles(id) on delete cascade,
  platform text not null check (platform in ('facebook_page')),
  page_id text not null,
  page_token text not null,
  is_active boolean not null default true,
  connected_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (agent_id, platform)
);

alter table agent_integrations enable row level security;
-- No policies added on purpose: only the service_role key (server-side,
-- inside a Netlify function) can touch this table.

create or replace view agent_integration_status as
  select agent_id, platform, is_active, connected_at
  from agent_integrations;

grant select on agent_integration_status to anon, authenticated;

-- Where each listing has been syndicated, and the outcome.
create table if not exists listing_posts (
  id bigint generated by default as identity primary key,
  listing_id bigint not null references listings(id) on delete cascade,
  platform text not null,
  status text not null check (status in ('posted', 'failed')),
  external_post_id text,
  external_url text,
  error_message text,
  posted_at timestamptz,
  created_at timestamptz not null default now()
);

alter table listing_posts enable row level security;
-- Service-role only for now (written by the fb-page-post function). A future
-- agent-facing "syndication history" view can add a scoped SELECT policy.

create index if not exists listing_posts_listing_id_idx on listing_posts (listing_id);
